apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cookiegpt-deployment-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: us-east-2
    objects: |
        - objectName: "openAIKey"
          objectType: "secretsmanager"